apiVersion: v1
kind: Service
metadata:
  name: roscore
spec:
  selector:
    app: wes-roscore
  ports:
    - name: ros
      protocol: TCP
      port: 11311
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wes-roscore
spec:
  selector:
    matchLabels:
      app: wes-roscore
  template:
    metadata:
      labels:
        app: wes-roscore
    spec:
      hostNetwork: true
      priorityClassName: wes-high-priority
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
        - name: wes-roscore
          image: lblanp/panda:plugin-roscore
          ports:
            - containerPort: 11311
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wes-plugin-network-policy-roscore
spec:
  podSelector:
    matchLabels:
      role: plugin
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: wes-roscore
      ports:
        - protocol: TCP
          port: 11311
