apiVersion: v1
kind: Service
metadata:
  name: roscore
spec:
  selector:
    app: roscore
  ports:
    - name: ros
      protocol: TCP
      port: 11311
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roscore
spec:
  selector:
    matchLabels:
      app: roscore
  template:
    metadata:
      labels:
        app: roscore
    spec:
      priorityClassName: wes-high-priority
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
        - name: roscore
          image: lblanp/panda:plugin-roscore
          ports:
            - containerPort: 11311
          env:
            - name: ROS_HOSTNAME
              value: "roscore"
            - name: ROS_MASTER_URI
              value: "http://roscore:11311"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wes-plugin-network-policy-roscore
spec:
  podSelector:
    matchLabels:
      role: plugin
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: roscore
      ports:
        - protocol: TCP
          port: 11311
