apiVersion: v1
kind: Service
metadata:
  name: roscore
spec:
  selector:
    app: roscore
  ports:
    - name: ros
      protocol: TCP
      port: 11311
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roscore
spec:
  serviceName: roscore
  selector:
    matchLabels:
      app: roscore
  template:
    metadata:
      labels:
        app: roscore
    spec:
      priorityClassName: wes-high-priority
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
        - name: roscore
          image: lblanp/panda:plugin-roscore
          ports:
            - containerPort: 11311
          env:
            - "ROS_HOSTNAME=localhost"
            - "ROS_MASTER_URI=http://roscore:11311"
