apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-dev-role
  namespace: dev
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list", "update", "patch"]
