apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wes-debugger
  labels:
    app.kubernetes.io/name: wes-debugger
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wes-debugger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wes-debugger
    spec:
      containers:
        - name: wes-debugger
          image: ubuntu:20.04
          args: ["bash", "-c", "while true; do sleep 1; done"]
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
          env:
            - name: WAGGLE_HOST_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - configMapRef:
                name: wes-identity
          volumeMounts:
            - name: host
              mountPath: /host/
              mountPropagation: HostToContainer
      volumes:
        - name: host
          hostPath:
            path: /
