apiVersion: v1
kind: Service
metadata:
  name: audio-server
spec:
  selector:
    app: audio-server
  ports:
    - name: pulseaudio
      protocol: TCP
      port: 4713
      targetPort: 4713
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-server
spec:
  selector:
    matchLabels:
      app: audio-server
  template:
    metadata:
      labels:
        app: audio-server
    spec:
      containers:
      - image: waggle/node-audio-server:0.0.2
        name: audio-server
        ports:
        - containerPort: 4713
