# Runs one instance of jetson-exporter on every node (DaemonSet) and expose
# the service on port 9100 on every node host.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jetson-exporter
  labels:
    app.kubernetes.io/name: jetson-exporter
    app.kubernetes.io/version: 0.0.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jetson-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jetson-exporter
        app.kubernetes.io/version: 0.0.0
    spec:
      nodeSelector:
        kubernetes.io/arch: "arm64"
        resource.gpu: "true"
      priorityClassName: wes-high-priority
      containers:
      - image: waggle/jetson-exporter:0.0.0
        name: jetson-exporter
        command: ["/app/jetson-exporter"]
        args:
        - --loadpath
        - /host/sys/devices/gpu.0/load
        env:
        - name: PORT
          value: "9101"
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
        ports:
        - name: http
          containerPort: 9101
          hostPort: 9101
        volumeMounts:
        - mountPath: /host/sys
          mountPropagation: HostToContainer
          name: sys
          readOnly: true
      volumes:
      - hostPath:
          path: /sys
        name: sys