# externalTrafficPolicy and internalTrafficPolicy make the metrics
# only available within the node
apiVersion: v1
kind: Service
metadata:
  name: wes-jetson-exporter-local
spec:
  selector:
    app: jetson-exporter
  ports:
    - name: http
      protocol: TCP
      port: 9101
      targetPort: http
  type: ClusterIP
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jetson-exporter
  labels:
    app.kubernetes.io/name: jetson-exporter
    app.kubernetes.io/version: 0.0.2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jetson-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jetson-exporter
        app.kubernetes.io/version: 0.0.2
        app: jetson-exporter
    spec:
      nodeSelector:
        kubernetes.io/arch: "arm64"
        resource.gpu: "true"
      priorityClassName: wes-high-priority
      containers:
        - image: waggle/jetson-exporter:0.0.2
          name: jetson-exporter
          command: ["/app/jetson-exporter"]
          args:
            - --loadpath
            - /host/sys/devices/gpu.0/load
          env:
            - name: PORT
              value: "9101"
            - name: KUBENODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
# (Todo) Yongho: this sometimes makes the pod use too much resources
# and create warnings and errors when the influxDB is throttled.
# This should be disabled until we can ensure this does not create the problems
#            - name: INFLUXDB_URL
#              value: http://wes-node-influxdb.default.svc.cluster.local:8086
#            - name: INFLUXDB_TOKEN
#              valueFrom:
#                secretKeyRef:
#                  name: wes-node-influxdb-waggle-token
#                  key: token
#            - name: INFLUXDB_ORG
#              value: waggle
#            - name: INFLUXDB_BUCKET
#              value: waggle
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              memory: 50Mi
          ports:
            - name: http
              containerPort: 9101
              hostPort: 9101
          volumeMounts:
            - mountPath: /host/sys
              mountPropagation: HostToContainer
              name: sys
              readOnly: true
      volumes:
        - hostPath:
            path: /sys
          name: sys