apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-upload-agent
  labels:
    app.kubernetes.io/name: node-upload-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-upload-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-upload-agent
    spec:
      containers:
      - image: waggle/node-upload-agent
        name: node-upload-agent
        resources:
          limits:
            cpu: 200m
            memory: 20Mi
          requests:
            cpu: 100m
            memory: 10Mi
        envFrom:
          - configMapRef:
              name: waggle-config
        volumeMounts:
        - name: waggle-ssh-key-secret
          mountPath: /etc/waggle
          readOnly: true
        - name: uploads
          mountPath: /uploads
        livenessProbe:
          exec:
            command:
            - rm
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 300
      volumes:
      - name: waggle-ssh-key-secret
        secret:
          secretName: waggle-ssh-key-secret
          defaultMode: 0600
      - name: uploads
        hostPath:
          path: /media/plugin-data/uploads
          type: DirectoryOrCreate
