# NOTE(sean) this deploys a privileged alpine container to each device in the cluster to allow
# debugging via kubernetes. we could eventually add tools to this image we may want later.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wes-debugger
  labels:
    app.kubernetes.io/name: wes-debugger
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wes-debugger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wes-debugger
    spec:
      containers:
      - image: alpine:latest
        name: wes-debugger
        args: ["sh", "-c", "while true; do sleep 60; done"]
        volumeMounts:
        - mountPath: /host/proc
          mountPropagation: HostToContainer
          name: proc
          readOnly: true
        - mountPath: /host/sys
          mountPropagation: HostToContainer
          name: sys
          readOnly: true
        - mountPath: /host/root
          mountPropagation: HostToContainer
          name: root
          readOnly: true
        securityContext:
          privileged: true
      hostNetwork: true
      hostPID: true
      volumes:
      - hostPath:
          path: /proc
        name: proc
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /
        name: root
