---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wes-plugin-role
  namespace: default
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
      - "nodes"
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wes-plugin-view
  namespace: default
roleRef:
  kind: ClusterRole
  name: wes-plugin-role
  apiGroup: rbac.authorization.k8s.io
  # `edit` is a built-in cluster role. more info about these can be found here:
  # https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles
subjects:
  - kind: ServiceAccount
    name: wes-plugin-account
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wes-plugin-account
