apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: wes-high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for WES components to ensure they are not preempted by plugins and user pods."
