apiVersion: v1
kind: Service
metadata:
  name: wes-audio-server
spec:
  selector:
    app: wes-audio-server
  ports:
    - name: pulseaudio
      protocol: TCP
      port: 4713
      targetPort: 4713
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wes-audio-server
spec:
  selector:
    matchLabels:
      app: wes-audio-server
  template:
    metadata:
      labels:
        app: wes-audio-server
    spec:
      priorityClassName: wes-high-priority
      nodeSelector:
        resource.microphone: "true"
      containers:
        - image: waggle/wes-audio-server:0.2.0
          name: wes-audio-server
          resources:
            limits:
              cpu: 500m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 10Mi
          ports:
            - containerPort: 4713
          securityContext:
            privileged: true
          # the main purpose of this service is the multiplex the usb microphone,
          # so we tie the readiness and liveness state to wheter or not we can see
          # the usb microphone.
          livenessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "pactl list sources | grep -q 'USB Audio'"
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 1
# TODO(sean) use device plugin to run on all devices with microphones
