# The wes-plugin-network-policy-default-deny network policy ensures that
# pods are "isolated" by default and require adding network permissions.
#
# See these examples:
# https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-ingress-traffic
# https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-egress-traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wes-plugin-network-policy-default-deny
spec:
  podSelector:
    matchLabels:
      role: plugin
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wes-plugin-network-policy-rabbitmq
spec:
  podSelector:
    matchLabels:
      role: plugin
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          role: backend
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wes-plugin-network-policy-audio-server
spec:
  podSelector:
    matchLabels:
      role: plugin
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: wes-audio-server
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wes-plugin-network-policy-playback-server
spec:
  podSelector:
    matchLabels:
      role: plugin
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: wes-playback-server
