apiVersion: apps/v1
kind: Deployment
metadata:
  name: wes-data-sharing-service
spec:
  selector:
    matchLabels:
      app: wes-data-sharing-service
  template:
    metadata:
      labels:
        app: wes-data-sharing-service
    spec:
      priorityClassName: wes-high-priority
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
        - name: wes-data-sharing-service
          image: waggle/wes-data-sharing-service:0.12.1
          resources:
            limits:
              cpu: 100m
              memory: 40Mi
            requests:
              cpu: 100m
              memory: 40Mi
          envFrom:
            - configMapRef:
                name: wes-identity
          env:
            - name: RABBITMQ_HOST
              value: "wes-rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: service
            - name: RABBITMQ_PASSWORD
              value: service
            - name: SYSTEM_USERS
              value: service
