apiVersion: batch/v1
kind: Job
metadata:
  name: init-chirpstack-server-job
spec:
  template:
    spec:
      containers:
      - name: init-chirpstack-server
        image: your_registry_username/your_image_name #TODO add the container name
        envFrom:
          - configMapRef:
              name: wes-identity
        env:
          - name: CHIRPSTACK_ACCOUNT_EMAIL
            value: "admin"
          - name: CHIRPSTACK_ACCOUNT_PASSWORD
            value: "admin"
          - name: CHIRPSTACK_API_INTERFACE
            value: "wes-chirpstack-server:8080"
      restartPolicy: OnFailure
  backoffLimit: 4
