- name: init
  hosts: all
  become: yes
  #remote_user: root

  tasks:
  - name: apt-get update
    apt:
      update_cache: yes
  - name: Ensure a locale exists
    community.general.locale_gen:
      name: en_US.UTF-8
      state: present


  - name: Install ubuntu packages
    apt:
      name:
        - systemd-sysv=245.4-4ubuntu3.3
        - python3=3.8.2-0ubuntu2
        - python3-pip=20.0.2-5ubuntu1.1
        - python3-venv=3.8.2-0ubuntu2  # what package needs this ?
      state: present
  - name: Creates directory
    file:
      path: /etc/sage/
      state: directory
  - name: config
    copy:
      dest: "/etc/sage/config.ini"
      content: |
        [system]
        devmode = true
        node-id-override = 0000000000000001

        [hardware]
        wlan-interface = eth0

  - name: disable ubuntu motd-news
    lineinfile:
      dest: /etc/default/motd-news
      state: present
      regexp: '^ENABLED='
      line: 'ENABLED=0'
  - name: Creates directory
    file:
      path: /etc/update-motd.d/
      state: directory
  - name: Copy file with owner and permissions
    copy:
      src: 05-sage
      dest: /etc/update-motd.d/05-sage
      owner: root
      group: root
      mode: '0755'

  # TODO: make sure this is downloaded only once
  # example: https://chaosmail.github.io/programming/2015/03/04/install-deb-packages-in-ansible/
  - name: Install waggle-registration
    apt:
      deb: https://github.com/waggle-sensor/beekeeper-registration/releases/download/v2.1.1/sagebk-registration_2.1.1.local-1097639_all.deb
  - name: Install waggle-reverse-tunnel
    apt:
      deb: https://github.com/waggle-sensor/beekeeper-registration/releases/download/v2.1.1/sagebk-reverse-tunnel_2.1.1.local-1097639_all.deb


- name: docker
  import_playbook: install-docker-playbook.yml



