
- name: waggle_config
  hosts: all
  become: yes
  #remote_user: root
  vars: 
    timezone_internal: "none"

  tasks:
    

    - name: set timezone variable if defined
      set_fact:
        timezone_internal: "{{timezone}}"
      when: timezone is defined

    - name: set timezone
      timezone:
        name: "{{timezone_internal}}"
      when: timezone_internal != "none"
    
    - name: Check if sage_registration exists
      stat:
        path: /etc/waggle/sage_registration
      register: reg_key_file

    - name: copy test keys (only if registration key does not exist)
      copy:
        src: "test-keys/{{item}}"
        dest: /etc/waggle/
        owner: root
        group: root
        mode: '0600'
      loop:
        - key.pem
        - key.pem-cert.pub
        - pubkey.pem
      when: not reg_key_file.stat.exists

    - name: Copy known_hosts (only if registration key does not exist)
      copy:
        src: test-keys/known_hosts
        dest: /etc/ssh/ssh_known_hosts
        owner: root
        group: root
        mode: '0644'
      when: not reg_key_file.stat.exists

    - name: node-id file
      copy:
        dest: "/etc/waggle/node-id"
        content: |
          ep-{{node_id}}
      when: not reg_key_file.stat.exists


    - name: config.ini (note that this file is created in the "os" playbook)
      community.general.ini_file:
        path: /etc/waggle/config.ini
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        mode: '0600'
      loop:
         - { section: 'system', option: 'devmode', value: 'true' }
         - { section: 'system', option: 'node-id-override', value: '{{node_id}}'  }



    - name: Make sure k3s is running
      systemd:
        state: started
        name: k3s

    # speed-up, otherwise have to wait up to 3 minutes
    #- name: Restart sagebk-registration.service
    #  systemd:
    #    state: restarted
    #    name: sagebk-registration.service

    # speed-up, otherwise have to wait up to 3 minute
    #- name: Restart sagebk-reverse-tunnel.service
    #  systemd:
    #    state: restarted
    #    name: sagebk-reverse-tunnel.service


    - name: Wait for nodes to be ready
      shell: "kubectl get nodes"
      register: nodes
      until:      
        - '" Ready "  in nodes.stdout'      
      retries: 20
      delay: 2

    - name: Creates directory
      file:
        path: /opt/sage/kubernetes
        state: directory

    - name: Ansible copy file to remote server
      copy:
        # ansible expects files in subfolder "files" (which does not exist), but we can get outside using "../"
        src: ../kubernetes
        dest: /opt/sage/


    - name: load kubernetes resources
      command: kubectl apply -k /opt/sage/kubernetes/    