# TODO use volume for managing private credentials
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-server
spec:
  selector:
    matchLabels:
      app: rabbitmq-server
  template:
    metadata:
      labels:
        app: rabbitmq-server
    spec:
      containers:
      # TODO consider using a configmap and use regular rabbitmq-server
      - image: waggle/node-rabbitmq-server:0.0.1
        name: rabbitmq-server
        ports:
        - containerPort: 15672
        - containerPort: 5672
        envFrom:
          - configMapRef:
              name: waggle-node-env
        volumeMounts:
        - name: waggle-node-private
          mountPath: /etc/certs
          readOnly: true
        command: ['/bin/sh', '-c']
        args: ['rm -rf /etc/waggle; cp -r /etc/certs /etc/waggle; chown -R rabbitmq:rabbitmq /etc/waggle/; chown -R rabbitmq:rabbitmq /etc/rabbitmq/; /docker-entrypoint.sh rabbitmq-server']
        # something broken here ?
        #- name: waggle-node-private
        #  mountPath: /etc/waggle
        #  readOnly: true
      volumes:
      - name: waggle-node-private
        secret:
          secretName: waggle-node-private
