# TODO use volume for managing private credentials
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-server
spec:
  selector:
    matchLabels:
      app: rabbitmq-server
  template:
    metadata:
      labels:
        app: rabbitmq-server
    spec:
      containers:
      - name: rabbitmq-server
        image: waggle/node-rabbitmq-server:0.0.1
        # command: ['/bin/sh', '-c']
        # args: ['rm -rf /etc/waggle; cp -r /etc/certs /etc/waggle; chown -R rabbitmq:rabbitmq /etc/waggle/; chown -R rabbitmq:rabbitmq /etc/rabbitmq/; /docker-entrypoint.sh rabbitmq-server']
        ports:
        - containerPort: 5672
        - containerPort: 15672
        envFrom:
        - configMapRef:
            name: waggle-config
        volumeMounts:
        - name: waggle-shovel-secret
          mountPath: /etc/waggle
          readOnly: true
      volumes:
      - name: waggle-shovel-secret
        secret:
          secretName: waggle-shovel-secret
          optional: true
