apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-server
spec:
  selector:
    app: rabbitmq-server
  ports:
    - name: rabbitmq-management
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
